spring.application.name=TrabalhoIndividualAPI

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/TrabalhoFinalAPI
spring.datasource.username=postgres
spring.datasource.password=1708

spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect